### ISSUE TITLE
Fields to fill out depending on participation 

### ISSUE THREAD

**Issue by famoser** [famoser/egoi-registration#2]
If only online, do not show `Immigtation` and `EventPresence` fields.
Are there any other fields online participants must fill out if not present at event?

**Comment by cneukom** [comment]
Which field is `EventPresence` referring to?

**Comment by famoser** [comment]
in the UI simply (and wrongly) referred to as Attendance (will resolve with #8).
At the moment the badge name, badge image, diet & allergies. 

Are any additional info besides personal data of online participatns required? It sounds reasonable they do not need neither immigration nor any of the event presence fields.
