### ISSUE TITLE
Editing Immigration & Attendance Details not possible

### ISSUE THREAD

**Issue by cneukom** [famoser/egoi-registration#4]
After providing initial data, I get an error 500 when attempting to edit the data again, see:
https://registration.egoi.org/participant/edit_immigration/C152DF55-2699-4C23-B4EC-962D24440206)

**Comment by cneukom** [comment]
Same applies for attendance, see https://registration.egoi.org/participant/edit_event_presence/C152DF55-2699-4C23-B4EC-962D24440206

**Comment by famoser** [comment]
is due to the file upload which is not implemented yet, fixed automatically in the future

**Comment by famoser** [comment]
this was resolved in #9
